version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    volumes:
      - ./script:/docker-entrypoint-initdb.d/
      - ../mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Kim-254500

  backend:
    container_name: backend
    image: quay.io/chisanuchakim/plutocart_backend
    restart: on-failure
    depends_on:
      - mysql
    # ports:
    #   - 8080:8080    
  backend-gateway:
    container_name: backend-gateway
    image: quay.io/chisanuchakim/plutocart_api_gateway
    volumes:
      - ./plutocart/plutocart_api_gateway/ssl/keystore.p12:/ssl
    environment:
      - KEY_STORE_PATH=/ssl/keystore.p12
    restart: on-failure
    depends_on:
      - backend
    ports:
      - 443:443    