name: timeup-runner

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Docker Container
        run: docker ps

      - name: Check Docker Images
        run: docker images

      - name: Delete Docker Container
        run: docker-compose down

      - name: Check if Docker image backend exists
        id: check_image_backend
        run: |
          if docker images quay.io/chisanuchakim/plutocart_backend | awk '{ print $1 ":" $2 }' | grep -q 'quay.io/chisanuchakim/plutocart_backend'; then
            echo "::set-output name=image_exists::true"
          else
            echo "::set-output name=image_exists::false"
          fi
        shell: bash

      - name: Remove Docker image backend if it exists
        if: steps.check_image_backend.outputs.image_exists == 'true'
        run: |
          docker rmi quay.io/chisanuchakim/plutocart_backend
          echo "Docker image backend removed."

      - name: Check if Docker image backend api gateway exists
        id: check_image_api_gateway
        run: |
          if docker images quay.io/chisanuchakim/plutocart_api_gateway | awk '{ print $1 ":" $2 }' | grep -q 'quay.io/chisanuchakim/plutocart_api_gateway'; then
            echo "::set-output name=image_exists::true"
          else
            echo "::set-output name=image_exists::false"
          fi
        shell: bash

      - name: Remove Docker image api gateway if it exists
        if: steps.check_image_api_gateway.outputs.image_exists == 'true'
        run: |
          docker rmi quay.io/chisanuchakim/plutocart_api_gateway
          echo "Docker image api gateway removed."

      - name: Build and push Docker images
        run: |
          cd /home/sysadmin/actions-runner/_work/plutocart/plutocart
          docker build -t backend -f backend.DockerFile .
          docker tag backend quay.io/chisanuchakim/plutocart_backend
          docker push quay.io/chisanuchakim/plutocart_backend
          docker build -t backend_api_gateway -f backend_api_gateway.DockerFile .
          docker tag backend_api_gateway quay.io/chisanuchakim/plutocart_api_gateway
          docker push quay.io/chisanuchakim/plutocart_api_gateway
          docker rmi backend backend_api_gateway
          docker-compose up -d

      - name: Prune Docker images
        run: |
          # Forcefully prune Docker objects and press "yes"
          docker image prune -f <<< 'yes'
        continue-on-error: true  # Continue even if Docker prune fails
